name: "Github Action Weather Bot"

on: 
    schedule: 
        - cron: '0 8 * * 1-5'

jobs:
    bot:
        steps:
            - name: "Install node" uses: actions/setup-node@v1
            - name: "Install dependancies" run: npm install
            - name: "Run code" 
            run: node index.js
            env:
                WEATHER_API_TOKEN: ${{ secrects.WEATHER_API_TOKEN }}
                TELEGRAM_BOT_TOKEN: ${{ secrects.TELEGRAM_BOT_TOKEN }}
                TELEGRAM_CHAT_ID: ${{ secrects.TELEGRAM_CHAT_ID }}