name: "Github Actions Weather Bot"

on: 
  push:
  schedule: 
    - cron: '0 8 * * 1-5'

jobs:
    bot:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: 'Install node'
          uses: actions/setup-node@v1
        - name: 'Install NPM dependencies'
          run: npm install
        - name: 'Run code'
          run: node index.js
          env:
            WEATHER_API_TOKEN: ${{ secrects.WEATHER_API_TOKEN }}
            TELEGRAM_BOT_TOKEN: ${{ secrects.TELEGRAM_BOT_TOKEN }}
            TELEGRAM_CHAT_ID: ${{ secrects.TELEGRAM_CHAT_ID }}